### ISSUE TITLE
IE Department's scraper isn't working.

### ISSUE THREAD

**Issue by furkansimsekli** [hacettepeoyt/hu-announcement-bot#2]
get_announcement() function must be fixed at IE class.

**Comment by furkansimsekli** [comment]
Ridicilous website. Scraper was alpha version tho, I don't have any intention to solve it due to anger!

**Comment by melikechan** [comment]
I think that the problem is _industrial engineering_ department's announcement come in two different versions:
![IMG_20220801_094354_655.jpg](https://user-images.githubusercontent.com/41804132/182090417-13b2946a-84c5-4fab-8ff6-a64828ea14fd.jpg) (there are two tags used for announcements)
- [ ] One is with `<p>` tags, which the scraper **only** scraps. This tag is used for announcements those don't contain details.
![IMG_20220801_094357_451.jpg](https://user-images.githubusercontent.com/41804132/182090348-86139715-4b76-4a5a-83ad-ed38ea458212.jpg) (here is the `<p>` tag)
- [ ] One is with `<details>` tags, the one scraper **doesn't** scrap. This tag is used for announcements which contain details. `<details>` has `<summary>`, which may be used for the header, and the rest for content.
