### ISSUE TITLE
Signal Support

### ISSUE THREAD

**Issue by div72** [hacettepeoyt/hu-announcement-bot#21]

**Comment by furkansimsekli** [comment]
As far as I know, Signal doesn't support bots. Do you have suggestion on Signal Support for Hacettepe Duyurucusu?

**Comment by div72** [comment]
Not natively but there are libraries for communicating over Signal like [signal-cli](https://github.com/AsamK/signal-cli). Considering the existence of Matrix-Signal bridges, it should not be against their ToS.

**Comment by melikechan** [comment]
Well, I actually hesitate to step in because I don't actually have much more experience in this field, but as far as I've read, there is a solution using dbus and signal-cli. (as mentioned above)
I have seen on this page, but I, unfortunately, can't understand the process. If someone wants to take a look, here is the link:
https://fabiobarbero.eu/posts/signalbot/

**Comment by furkansimsekli** [comment]
I see.. It'd be nice to have a platform other than Telegram but I don't think I'll work on it in near future. If anyone interested in, they can contribute freely.

**Comment by furkansimsekli** [comment]
In the #22 , @div72 did a really good job but the problem was that Signal doesn't have well-supported API for our use case. That's why I believe maintaining would have been hard for that reason. The desing was really neat for my standards and I checked on it time to time while writing v3.

And with #24 , HD really became PTB dependent bot. The design is shaped around their implementations.  Is this really *that* vital? No, of course we can use the Telegram REST API manually and do the scheduling and concurrency ourselves. However, I like what they do in PTB and that's why shaping around them doesn't sound bad.

Until a big Signal update for developers, this issue will remain closed.
