### ISSUE TITLE
Automation of Translation

### ISSUE THREAD

**Issue by ece-etoglu** [hacettepeoyt/hu-announcement-bot#46]
I think it would be easier to support multiple languages if the translation process was automated. 
There is a cool python package for translations:  https://pypi.org/project/translate/

**Comment by furkansimsekli** [comment]
That looks cool and can make HD to have lots of language support tbh. I have two concerns though, one of them is the speed, and other one is *odd* translations. Speed is important because how quicker to send a response to the Telegram how better it is, since it will work online it may affect take a bit time. And even though online translations have come a long way last couple of years, I still think they can be sometimes unexpected.

I'll test it with the current messages, and will see the performance then. Thank you for the suggestion!

**Comment by furkansimsekli** [comment]
Alright, speed problem can be easily solved by just creating the translation once and storing them.

BUT translations are not good. I tested all of them from English to Turkish, and even though you can get the main idea, the sentences don't feel right as you might suspect. Also uppercases and lowercases are appearing random in the translations, and I don't understand but I also saw some random numbers in the department names. Maybe these can be improved if I use another provider, but I don't think it can compete with the manual translations =)

I'm thinking to send a message to everyone and invite them to contribute to the project by adding new translations. There are many people from different language schools, and different nationalities in the university.
